car_booking/urls.py
from django.contrib import admin
from django.urls import include, path
from car_booking.views import home_view

urlpatterns = [
    path("", home_view, name="home"),
    path("admin/", admin.site.urls),
    path("cars/", include("cars.urls")),
    path("management/", include("management.urls")),
]

cars/urls.py
from django.urls import include, path

from cars.views import (
    CarsListView,
    CarDetailView,
    create_reservation,
    delete_reservation,
    ReservationDetailView,
)


urlpatterns = [
    path("", CarsListView.as_view(), name="cars-list"),
    path("<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("<int:pk>/reserve", create_reservation, name="car-reserve"),
    path("reservation/<int:pk>/delete/", delete_reservation, name="delete-reservation"),
    path(
        "reservation/<int:pk>/",
        ReservationDetailView.as_view(),
        name="reservation-detail",
    ),
]

cars/models.py
from django.db import models
from management.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import os
import random
from django.db.models import Q


class Car(models.Model):
    TRANSMISSION_CHOICES = [
        ("manual", "Manualna"),
        ("automatic", "Automatyczna"),
    ]

    FUEL_TYPE_CHOICES = [
        ("petrol", "Benzyna"),
        ("diesel", "Diesel"),
        ("electric", "Elektryczny"),
        ("hybrid", "Hybrydowy"),
    ]

    CAR_TYPE_CHOICES = [
        ("sedan", "Sedan"),
        ("hatchback", "Hatchback"),
        ("suv", "SUV"),
        ("coupe", "Coupe"),
        ("convertible", "Kabriolet"),
        ("wagon", "Kombi"),
    ]

    DOORS_CHOICES = [(2, 2), (3, 3), (4, 4), (5, 5)]
    SEATS_CHOICES = [(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]

    brand = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    year = models.PositiveIntegerField(
        validators=[MinValueValidator(1999), MaxValueValidator(2025)]
    )
    daily_rate = models.DecimalField(max_digits=10, decimal_places=2)
    doors = models.PositiveIntegerField(choices=DOORS_CHOICES)
    car_type = models.CharField(max_length=20, choices=CAR_TYPE_CHOICES)
    transmission = models.CharField(max_length=10, choices=TRANSMISSION_CHOICES)
    seats = models.PositiveIntegerField(choices=SEATS_CHOICES)
    fuel_type = models.CharField(max_length=10, choices=FUEL_TYPE_CHOICES)
    trunk_size = models.PositiveIntegerField(help_text="Pojemność bagażnika w litrach")
    image = models.CharField(max_length=255, blank=True, null=True)

    @property
    def name(self) -> str:
        return f"{self.brand} {self.model}"

    @property
    def is_reserved(self):
        return self.reservations.all().exists()

    def __str__(self) -> str:
        return f"{self.brand} {self.model} ({self.year}) Samochód {self.name} id: {self.id}"

    @staticmethod
    def assign_random_photo() -> str | None:
        photos_dir = os.path.join("cars", "static", "car_photos")
        valid_extensions = {".jpeg", ".jpg", ".png"}

        photos = [
            file
            for file in os.listdir(photos_dir)
            if os.path.isfile(os.path.join(photos_dir, file))
            and os.path.splitext(file)[1].lower() in valid_extensions
        ]

        if photos:
            return f"car_photos/{random.choice(photos)}"
        return None

    def save(self, *args: tuple, **kwargs: dict) -> None:
        if not self.image:
            self.image = self.assign_random_photo()
        super().save(*args, **kwargs)

    def is_selected_days_reserved(self, new_start_date, new_end_date):
        check = Car.get_selected_days_reserved_filter(new_start_date, new_end_date)
        return Car.objects.filter(check, id=self.id).exists()

    @staticmethod
    def get_selected_days_reserved_filter(new_start_date, new_end_date):
        return Q(
            reservations__start_date__lt=new_end_date,
            reservations__end_date__gt=new_start_date,
        )


class Reservation(models.Model):
    car = models.ForeignKey(Car, on_delete=models.PROTECT, related_name="reservations")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField(verbose_name="Początek rezerwacji")
    end_date = models.DateField(verbose_name="Koniec rezerwacji")

    def __str__(self) -> str:
        return f"Reservation {self.id} for car {self.car.name}"

cars/forms.py
from django.forms import ModelForm, ValidationError, widgets
from django.utils.timezone import now
from datetime import date
from cars.models import Reservation


class ReservationForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.car = kwargs.pop("car", None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = Reservation
        fields = ["start_date", "end_date"]
        widgets = {
            "start_date": widgets.DateInput(attrs={"type": "date"}),
            "end_date": widgets.DateInput(attrs={"type": "date"}),
        }

    def clean_start_date(self) -> date:
        start_date: date = self.cleaned_data["start_date"]
        date_now = now()
        today: date = date(date_now.year, date_now.month, date_now.day)
        if start_date < today:
            raise ValidationError(
                "Data początkowa rezerwacji nie może być z przeszłości."
            )
        return start_date

    def clean_end_date(self) -> date:
        end_date: date = self.cleaned_data["end_date"]
        date_now = now()
        today: date = date(date_now.year, date_now.month, date_now.day)
        if end_date < today:
            raise ValidationError("Data końcowa rezerwacji nie może być z przeszłości.")
        return end_date

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")

        if start_date and end_date and end_date < start_date:
            raise ValidationError(
                "Data końcowa nie może być wcześniejsza niż data początkowa."
            )

        if start_date and end_date and self.car:
            overlapping_reservations = Reservation.objects.filter(
                car=self.car,
                start_date__lte=end_date,
                end_date__gte=start_date,
            )
            if overlapping_reservations.exists():
                raise ValidationError(
                    "Samochód jest już zarezerwowany w wybranym terminie."
                )
        return cleaned_data

cars/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.decorators.csrf import csrf_protect
from django.http import HttpRequest, HttpResponse
from cars.models import Car, Reservation
from cars.filters import CarFilter
from cars.forms import ReservationForm
from django_filters.views import FilterView
from typing import Any
from django.contrib.auth.decorators import login_required


class CarsListView(FilterView):
    model = Car
    template_name = "cars_list.html"
    filterset_class = CarFilter
    context_object_name = "object_list"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["record_count"] = context["object_list"].count()
        return context


class CarDetailView(DetailView):
    model = Car
    template_name = "car_detail.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["form"] = ReservationForm()
        return context


@csrf_protect
def create_reservation(request: HttpRequest, pk: int) -> HttpResponse:
    car = get_object_or_404(Car, pk=pk)
    if request.method == "POST" and request.user.is_authenticated:
        form = ReservationForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data["start_date"]
            end_date = form.cleaned_data["end_date"]

            overlapping_reservations = Reservation.objects.filter(
                car=car,
                start_date__lte=end_date,
                end_date__gte=start_date,
            )
            if overlapping_reservations.exists():
                form.add_error(
                    None, "Samochód jest już zarezerwowany w wybranym terminie."
                )
            else:
                Reservation.objects.create(
                    car=car,
                    user=request.user,
                    start_date=start_date,
                    end_date=end_date,
                )
                return redirect("user-detail", request.user.id)

        return render(request, "car_detail.html", {"car": car, "form": form})

    return redirect("cars-list")


@login_required
def delete_reservation(request: HttpRequest, pk: int) -> HttpResponse:
    reservation = get_object_or_404(Reservation, pk=pk, user=request.user)
    reservation.delete()
    return redirect("user-detail", request.user.id)


class ReservationDetailView(DetailView):
    model = Reservation
    template_name = "reservation_detail.html"
    context_object_name = "reservation"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reservation = self.get_object()

        days = (reservation.end_date - reservation.start_date).days + 1
        total_price = days * reservation.car.daily_rate

        context["total_price"] = total_price
        return context

cars/templates/car_detail.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ car.brand }} {{ car.model }}</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<!-- Menu -->
<div class="top-bar">
    <a href="{% url 'cars-list' %}" class="logo">CarBooking</a>
    <div class="nav-links">
        <a href="{% url 'cars-list' %}">Lista samochodów</a>
        <a href="{% url 'user-detail' request.user.id %}">Profil użytkownika</a>
        <form method="post" action="{% url 'logout' %}" style="margin: 0;">
            {% csrf_token %}
            <button type="submit" class="logout-btn">Wyloguj</button>
        </form>
    </div>
</div>

<!-- Main -->
<div class="car-detail-container">
    <h1>{{ car.brand }} {{ car.model }}</h1>

    <div class="car-detail-content">
        <!-- Tabela szczegółów -->
        <div class="table-container cardetail">
            <table class="table cardetail">
                <tbody>
                <tr>
                    <th>Rok produkcji</th>
                    <td>{{ car.year }}</td>
                </tr>
                <tr>
                    <th>Typ nadwozia</th>
                    <td>{{ car.get_car_type_display }}</td>
                </tr>
                <tr>
                    <th>Typ paliwa</th>
                    <td>{{ car.get_fuel_type_display }}</td>
                </tr>
                <tr>
                    <th>Typ skrzyni biegów</th>
                    <td>{{ car.get_transmission_display }}</td>
                </tr>
                <tr>
                    <th>Pojemność bagażnika</th>
                    <td>{{ car.trunk_size }} l</td>
                </tr>
                <tr>
                    <th>Liczba drzwi</th>
                    <td>{{ car.doors }}</td>
                </tr>
                <tr>
                    <th>Liczba miejsc</th>
                    <td>{{ car.seats }}</td>
                </tr>
                </tbody>
            </table>
            <div class="price">Stawka dzienna: {{ car.daily_rate }} zł</div>
        </div>

        <!-- Zdjecie samochodu -->
        <div class="car-image-container">
            {% if car.image %}
            <img src="{% static car.image %}" alt="{{ car.brand }} {{ car.model }}">
            {% else %}
            <div class="placeholder">Brak zdjęcia</div>
            {% endif %}
        </div>
    </div>

    <div class="reservation-box cardetail">
        <h2>Zarezerwuj samochód</h2>
        <form method="POST" action="{% url 'car-reserve' car.id %}">
            {% csrf_token %}
            <div class="form-container cardetail">
                <div class="date-fields cardetail">
                    {% for field in form %}
                    <div class="fieldWrapper cardetail">
                        {{ field.label_tag }} {{ field }}
                        {% if field.errors %}
                        <div class="error">{{ field.errors|join:", " }}</div>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
                {% if form.non_field_errors %}
                <div class="validation-error cardetail">{{ form.non_field_errors|join:", " }}</div>
                {% endif %}
                <input type="submit" value="Rezerwuj">
            </div>
        </form>
    </div>
    <div>
        <a href="{% url 'cars-list' %}" class="btn">Powrót listy</a>
    </div>

</div>
</body>
</html>

cars/templates/cars_list.html
<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Lista samochodów</title>

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"> {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body>
    <!-- Menu -->
    <div class="top-bar">
        <a href="{% url 'cars-list' %}" class="logo">CarBooking</a>
        <div class="nav-links">
            <a href="{% url 'cars-list' %}">Lista samochodów</a>
            <a href="{% url 'user-detail' request.user.id %}">Profil użytkownika</a>
            <form method="post" action="{% url 'logout' %}" style="margin: 0;">
                {% csrf_token %}
                <button type="submit" class="logout-btn">Wyloguj</button>
            </form>
        </div>
    </div>

    <!-- Main -->
    <div class="list-container">
        <!-- Box z filtrowaniem -->
        <div class="list-filter-box">
            <form method="get">
                <div class="list-filter-section">
                    <h2>Dane techniczne</h2> {{ filter.form.brand.label_tag }} {{ filter.form.brand }} {{ filter.form.seats.label_tag }} {{ filter.form.seats }} {{ filter.form.car_type.label_tag }} {{ filter.form.car_type }} {{ filter.form.fuel_type.label_tag }} {{ filter.form.fuel_type }} {{ filter.form.transmission.label_tag }} {{ filter.form.transmission }}
                </div>
                <div class="list-filter-section">
                    <h2>Dostępność w datach</h2> {{ filter.form.start_date.label_tag }} {{ filter.form.start_date }} {{ filter.form.end_date.label_tag }} {{ filter.form.end_date }}
                </div>
                <div class="list-filter-actions">
                    <button type="submit" class="list-filter-btn">Filtruj</button>
                    <a href="{% url 'cars-list' %}" class="list-reset-btn">Resetuj</a>
                </div>
            </form>
        </div>

        <!-- Liczba dostępnych samochodów -->
        <p class="list-record-info">Liczba dostępnych samochodów: {{ record_count }}</p>

        {% if object_list %}
        <div class="list-cars-grid">
            {% for car in object_list %}
            <div class="list-car-card">
                {% if car.image %}
                <img src="{% static car.image %}" alt="{{ car.brand }} {{ car.model }}"> {% else %}
                <img src="{% static 'default.jpg' %}" alt="Default Image"> {% endif %}
                <div class="name">{{ car.brand }} {{ car.model }}</div>
                <div class="list-details">
                    <i class="fas fa-gas-pump"></i> {{ car.get_fuel_type_display }}
                    <br>
                    <i class="fas fa-car"></i> {% if car.get_transmission_display == "Automatyczna" %} Automat {% elif car.get_transmission_display == "Manualna" %} Manual {% else %} {{ car.get_transmission_display }} {% endif %}
                    <br>
                    <i class="fas fa-users"></i> {{ car.seats }}
                </div>
                <a href="{% url 'car-detail' car.id %}" class="list-details-btn">Wybierz</a>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p class="list-no-cars">Brak samochodów spełniających wybrane kryteria. Spróbuj zmienić ustawienia filtrowania.</p>
        {% endif %}
    </div>
</body>

</html>

cars/templates/reservation_detail.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Szczegóły rezerwacji</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<!-- Menu -->
<div class="top-bar">
    <a href="{% url 'cars-list' %}" class="logo">CarBooking</a>
    <div class="nav-links">
        <a href="{% url 'cars-list' %}">Lista samochodów</a>
        <a href="{% url 'user-detail' reservation.user.id %}">Profil użytkownika</a>
        <form method="post" action="{% url 'logout' %}" style="margin: 0;">
            {% csrf_token %}
            <button type="submit" class="logout-btn">Wyloguj</button>
        </form>
    </div>
</div>

<!-- Main -->
<div class="reservation-container">
    <h1>Szczegóły rezerwacji</h1>

    <!-- Dates -->
    <div class="reservation-dates">
        <p>Początek rezerwacji: <span>{{ reservation.start_date }}</span></p>
        <p>Koniec rezerwacji: <span>{{ reservation.end_date }}</span></p>
    </div>


    <div class="reservation-content">

        <div class="car-image-container">
            {% if reservation.car.image %}
            <img src="{% static reservation.car.image %}" alt="{{ reservation.car.brand }} {{ reservation.car.model }}">
            {% else %}
            <div class="placeholder">Brak zdjęcia</div>
            {% endif %}
        </div>
        <!-- Tabela szczegółów -->
        <table class="table reservation">
            <tbody>
            <th><h2>{{ reservation.car.brand }} {{ reservation.car.model }} </h2></th>

            <tr>
                <th scope="row"><br>Typ samochodu</th>
                <td>{{ reservation.car.get_car_type_display }}</td>
            </tr>
            <tr>
                <th scope="row"><br>Typ paliwa</th>
                <td>{{ reservation.car.get_fuel_type_display }}</td>
            </tr>
            <tr>
                <th scope="row"><br>Pojemność bagażnika</th>
                <td>{{ reservation.car.trunk_size }} l</td>
            </tr>
            <tr>
                <th scope="row"><br>Liczba drzwi</th>
                <td>{{ reservation.car.doors }}</td>
            </tr>
            <tr>
                <th scope="row"><br>Liczba miejsc</th>
                <td>{{ reservation.car.seats }}</td>
            </tr>
            </tbody>
        </table>
    </div>


    <!-- Cena -->
    <div class="price-label">
        Kwota do zapłaty: {{ total_price }} zł
    </div>

    <div>
        <a href="{% url 'user-detail' reservation.user.id %}" class="btn">Powrót do rezerwacji</a>
    </div>
</div>
</body>
</html>